# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  openstack_repo = 'https://repos.fedorapeople.org/repos/openstack/openstack-juno/rdo-release-juno-1.noarch.rpm'
  openio_mirror = ENV['OIO_MIRROR'] || 'http://mirror.openio.io/pub/repo/openio/sds'

  if ARGV[0] =~ /^up|provision$/i and not ARGV.include?("--no-provision")
    # Get OpenIO-SDS IPs
    res = `VBoxManage guestproperty get OpenIO-SDS /VirtualBox/GuestInfo/Net/1/V4/IP`
    if $? != 0
      puts "Error: OpenIO-SDS Virtual Machine is not running or cannot get Host-Only IP. Aborting."
      exit 1
    end
    openio_sds_ipaddr = res.split[1]
  end

  # Box configuration
  config.vm.box = "openio/sds-ext-swift"
  config.vm.network "private_network", :type => 'dhcp', :adapter => 2
  config.vm.network "public_network" , :type => 'dhcp', :adapter => 3

  # use "openio" as default user instead of "vagrant"
  config.ssh.username = "openio"
  config.ssh.pty = true
  config.vm.synced_folder '.', '/var/lib/oio/vagrant', disabled: true

  # VirtualBox Specific
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.gui = true
    virtualbox.name = "OpenIO-SDS-ext-swift"
    virtualbox.cpus = "1"
    virtualbox.memory = "512"
  end

  # VMware Fusion/Workstation Specfic
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.vmx['displayname'] = "OpenIO-SDS-ext-swift"
    vmware.vmx["numvcpus"] = "1"
    vmware.vmx["memsize"] = "512"
  end

  # Provisionning OpenIO SDS
  config.vm.provision "shell", inline:  <<-SHELL
    /usr/bin/yum -y install wget
    release=$(/bin/wget #{openio_mirror}/latest -q -O -)
    /usr/bin/yum -y install http://mirror.openio.io/pub/repo/openio/sds/\$release/el/openio-sds-release-\$release-1.el.noarch.rpm #{openstack_repo}
    /usr/bin/yum -y install puppet-openio-sds-profile-vagrant-ext-swift memcached python-swiftclient
    /usr/bin/puppet module install stackforge-keystone
    /usr/bin/systemctl enable memcached.service
    /usr/bin/systemctl start memcached.service
    /usr/share/puppet/modules/openiosds/profiles/install.sh vagrant-ext-swift #{openio_sds_ipaddr}
    echo "export OS_TENANT_NAME=demo
export OS_USERNAME=demo
export OS_PASSWORD=DEMO_PASS
export OS_AUTH_URL=http://localhost:5000/v2.0" \
      > ~openio/keystonerc_demo
  SHELL

end
