# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Gloval env variables
  openio_mirror = ENV['OIO_MIRROR'] || 'http://mirror.openio.io/pub/repo/openio/sds'

  # Box configuration
  config.vm.box = "openio/sds"
  config.vm.network "private_network", :type => 'dhcp', :adapter => 2
  config.vm.network "public_network" , :type => 'dhcp', :adapter => 3
  config.vm.synced_folder '.', '/var/lib/oio/vagrant', disabled: true

  # use "openio" as default user instead of "vagrant"
  config.ssh.username = "openio"
  config.ssh.password = ""

  # VirtualBox Specific
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.gui = true
    virtualbox.name = "OpenIO-CentOS7"
    virtualbox.cpus = "1"
    virtualbox.memory = "768"
  end

  # Provisionning OpenIO SDS
  config.vm.provision "shell", inline: <<-SHELL
    /usr/bin/yum -y install wget
    release=$(/bin/wget #{openio_mirror}/latest -q -O -)
    /usr/bin/yum -y install http://mirror.openio.io/pub/repo/openio/sds/\$release/el/openio-sds-release-\$release-1.el.noarch.rpm #{add_repo}
  SHELL

end
